# Generated by Django 4.0.3 on 2022-03-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.FloatField()),
                ('weight', models.FloatField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='sizes'
        ),
        migrations.AddField(
            model_name='dish',
            name='sizes',
            field=models.ManyToManyField(through='dishes.DishSize', to='dishes.sizetype'),
        ),
        migrations.AddField(
            model_name='dishsize',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
        ),
        migrations.AddField(
            model_name='dishsize',
            name='size_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.sizetype'),
        ),
    ]
